# Generated by Django 4.2.1 on 2023-05-21 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonDRF', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_ids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LittleLemonDRF.order'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order_ids', 'menuitem')},
        ),
    ]
